// Code generated by hertz generator. DO NOT EDIT.

package user

import (

	"github.com/cloudwego/hertz/pkg/app/server"
	"west2-video/gateway/biz/handler"
	"west2-video/gateway/biz/midd"
	"west2-video/gateway/biz/router/routerRepo"
)
func NewInteractionRouter()*InteractionRouter {
	return &InteractionRouter{}
}
type InteractionRouter struct{

}
// GeneratedRegister registers routers generated by IDL.
func (rr *InteractionRouter)Router(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	// 互动相关路由
	interaction := r.Group("/interaction").Use(midd.AuthMiddleware())
	{
		interaction.POST("/like",  handler.LikeAction)         // 点赞操作
		interaction.GET("/like/list", handler.LikeList)      // 点赞列表
		interaction.POST("/comment", handler.CommentAction)   // 评论
		interaction.GET("/comment/list", handler.CommentList)  // 评论列表
		interaction.DELETE("/comment", handler.DeleteComment) // 删除评论
	}


}
func init() {
	router := NewInteractionRouter()
	routerRepo.Register(router)
}