// Code generated by hertz generator. DO NOT EDIT.

package user

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"west2-video/gateway/biz/handler"
	"west2-video/gateway/biz/midd"
	"west2-video/gateway/biz/router/routerRepo"
)

func NewUserRouter() *UserRouter {
	return &UserRouter{}
}

type UserRouter struct {
}

// GeneratedRegister registers routers generated by IDL.
func (rr *UserRouter) Router(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	r.GET("/ping", handler.Ping)
	// 用户相关路由
	user := r.Group("/user")
	{
		user.POST("/register", handler.Register)           // 注册
		user.POST("/login", handler.Login)                  // 登录
		user.GET("/refresh",  handler.RefreshToken) // 刷新token
		user.GET("/info", midd.AuthMiddleware(), handler.GetUserInfo) // 用户信息
		user.PUT("/avatar/upload", midd.AuthMiddleware(), handler.UploadAvatar) // 上传头像
		user.POST("/search/image", midd.AuthMiddleware(), handler.SearchByImage) // 以图搜图
	}
	r.GET("/auth/mfa/qrcode", midd.AuthMiddleware(), handler.GetMfaQrcode) // 获取 MFA qrcode
	r.POST("/mfa/bind", midd.AuthMiddleware(), handler.BindMfa) // 绑定 MFA
}
func init() {
	router := NewUserRouter()
	routerRepo.Register(router)
}
