// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: api/interaction/interaction.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	v11 "west2-video/api/common/v1"
	v1 "west2-video/api/user/v1"
	v12 "west2-video/api/video/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========= 评论通用结构 (Comment Message) =========
// Aligned with the 'comments' table in database/init.sql
type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VideoId       int64                  `protobuf:"varint,2,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	User          *v1.User               `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`                                // Populated by the service layer
	ParentId      int64                  `protobuf:"varint,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`       // Added to match SQL
	LikeCount     int64                  `protobuf:"varint,6,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`    // Added to match SQL
	ChildCount    int64                  `protobuf:"varint,7,opt,name=child_count,json=childCount,proto3" json:"child_count,omitempty"` // Added to match SQL
	Content       string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *v11.Timestamp         `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *v11.Timestamp         `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`       // Added to match SQL
	DeletedAt     *v11.Timestamp         `protobuf:"bytes,11,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"` // Added to match SQL, optional for nullability
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_api_interaction_interaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_api_interaction_interaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_api_interaction_interaction_proto_rawDescGZIP(), []int{0}
}

func (x *Comment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *Comment) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Comment) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Comment) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Comment) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Comment) GetChildCount() int64 {
	if x != nil {
		return x.ChildCount
	}
	return 0
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetCreatedAt() *v11.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Comment) GetUpdatedAt() *v11.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Comment) GetDeletedAt() *v11.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

// ========= 点赞操作 =========
type LikeActionRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	VideoId int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	// action_type: 1 点赞, 2 取消点赞
	ActionType    int32 `protobuf:"varint,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeActionRequest) Reset() {
	*x = LikeActionRequest{}
	mi := &file_api_interaction_interaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeActionRequest) ProtoMessage() {}

func (x *LikeActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_interaction_interaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeActionRequest.ProtoReflect.Descriptor instead.
func (*LikeActionRequest) Descriptor() ([]byte, []int) {
	return file_api_interaction_interaction_proto_rawDescGZIP(), []int{1}
}

func (x *LikeActionRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *LikeActionRequest) GetActionType() int32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

type LikeActionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v11.BaseResponse      `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeActionReply) Reset() {
	*x = LikeActionReply{}
	mi := &file_api_interaction_interaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeActionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeActionReply) ProtoMessage() {}

func (x *LikeActionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_interaction_interaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeActionReply.ProtoReflect.Descriptor instead.
func (*LikeActionReply) Descriptor() ([]byte, []int) {
	return file_api_interaction_interaction_proto_rawDescGZIP(), []int{2}
}

func (x *LikeActionReply) GetBase() *v11.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

// ========= 点赞列表 =========
type LikeListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          *v11.PageRequest       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeListRequest) Reset() {
	*x = LikeListRequest{}
	mi := &file_api_interaction_interaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeListRequest) ProtoMessage() {}

func (x *LikeListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_interaction_interaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeListRequest.ProtoReflect.Descriptor instead.
func (*LikeListRequest) Descriptor() ([]byte, []int) {
	return file_api_interaction_interaction_proto_rawDescGZIP(), []int{3}
}

func (x *LikeListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LikeListRequest) GetPage() *v11.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type LikeListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v11.BaseResponse      `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Videos        []*v12.Video           `protobuf:"bytes,2,rep,name=videos,proto3" json:"videos,omitempty"`
	Page          *v11.PageResponse      `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeListReply) Reset() {
	*x = LikeListReply{}
	mi := &file_api_interaction_interaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeListReply) ProtoMessage() {}

func (x *LikeListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_interaction_interaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeListReply.ProtoReflect.Descriptor instead.
func (*LikeListReply) Descriptor() ([]byte, []int) {
	return file_api_interaction_interaction_proto_rawDescGZIP(), []int{4}
}

func (x *LikeListReply) GetBase() *v11.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *LikeListReply) GetVideos() []*v12.Video {
	if x != nil {
		return x.Videos
	}
	return nil
}

func (x *LikeListReply) GetPage() *v11.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// ========= 评论 =========
type CommentActionRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	VideoId int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Content string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// comment_id 字段题目说本次不要求实现，这里仅保留以兼容文档
	CommentId     int64 `protobuf:"varint,3,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentActionRequest) Reset() {
	*x = CommentActionRequest{}
	mi := &file_api_interaction_interaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentActionRequest) ProtoMessage() {}

func (x *CommentActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_interaction_interaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentActionRequest.ProtoReflect.Descriptor instead.
func (*CommentActionRequest) Descriptor() ([]byte, []int) {
	return file_api_interaction_interaction_proto_rawDescGZIP(), []int{5}
}

func (x *CommentActionRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *CommentActionRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommentActionRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type CommentActionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v11.BaseResponse      `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Comment       *Comment               `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentActionReply) Reset() {
	*x = CommentActionReply{}
	mi := &file_api_interaction_interaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentActionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentActionReply) ProtoMessage() {}

func (x *CommentActionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_interaction_interaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentActionReply.ProtoReflect.Descriptor instead.
func (*CommentActionReply) Descriptor() ([]byte, []int) {
	return file_api_interaction_interaction_proto_rawDescGZIP(), []int{6}
}

func (x *CommentActionReply) GetBase() *v11.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CommentActionReply) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

// ========= 评论列表 =========
type CommentListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       int64                  `protobuf:"varint,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Page          *v11.PageRequest       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentListRequest) Reset() {
	*x = CommentListRequest{}
	mi := &file_api_interaction_interaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentListRequest) ProtoMessage() {}

func (x *CommentListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_interaction_interaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentListRequest.ProtoReflect.Descriptor instead.
func (*CommentListRequest) Descriptor() ([]byte, []int) {
	return file_api_interaction_interaction_proto_rawDescGZIP(), []int{7}
}

func (x *CommentListRequest) GetVideoId() int64 {
	if x != nil {
		return x.VideoId
	}
	return 0
}

func (x *CommentListRequest) GetPage() *v11.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type CommentListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v11.BaseResponse      `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Comments      []*Comment             `protobuf:"bytes,2,rep,name=comments,proto3" json:"comments,omitempty"`
	Page          *v11.PageResponse      `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentListReply) Reset() {
	*x = CommentListReply{}
	mi := &file_api_interaction_interaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentListReply) ProtoMessage() {}

func (x *CommentListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_interaction_interaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentListReply.ProtoReflect.Descriptor instead.
func (*CommentListReply) Descriptor() ([]byte, []int) {
	return file_api_interaction_interaction_proto_rawDescGZIP(), []int{8}
}

func (x *CommentListReply) GetBase() *v11.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CommentListReply) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *CommentListReply) GetPage() *v11.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// ========= 删除评论 =========
type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     int64                  `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_api_interaction_interaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_interaction_interaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_api_interaction_interaction_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCommentRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type DeleteCommentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v11.BaseResponse      `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentReply) Reset() {
	*x = DeleteCommentReply{}
	mi := &file_api_interaction_interaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentReply) ProtoMessage() {}

func (x *DeleteCommentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_interaction_interaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentReply.ProtoReflect.Descriptor instead.
func (*DeleteCommentReply) Descriptor() ([]byte, []int) {
	return file_api_interaction_interaction_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCommentReply) GetBase() *v11.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_api_interaction_interaction_proto protoreflect.FileDescriptor

const file_api_interaction_interaction_proto_rawDesc = "" +
	"\n" +
	"!api/interaction/interaction.proto\x12\x12api.interaction.v1\x1a\x15api/common/base.proto\x1a\x15api/video/video.proto\x1a\x13api/user/user.proto\"\xaa\x03\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bvideo_id\x18\x02 \x01(\x03R\avideoId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12%\n" +
	"\x04user\x18\x04 \x01(\v2\x11.api.user.v1.UserR\x04user\x12\x1b\n" +
	"\tparent_id\x18\x05 \x01(\x03R\bparentId\x12\x1d\n" +
	"\n" +
	"like_count\x18\x06 \x01(\x03R\tlikeCount\x12\x1f\n" +
	"\vchild_count\x18\a \x01(\x03R\n" +
	"childCount\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x127\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x18.api.common.v1.TimestampR\tcreatedAt\x127\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x18.api.common.v1.TimestampR\tupdatedAt\x12<\n" +
	"\n" +
	"deleted_at\x18\v \x01(\v2\x18.api.common.v1.TimestampH\x00R\tdeletedAt\x88\x01\x01B\r\n" +
	"\v_deleted_at\"O\n" +
	"\x11LikeActionRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\x05R\n" +
	"actionType\"B\n" +
	"\x0fLikeActionReply\x12/\n" +
	"\x04base\x18\x01 \x01(\v2\x1b.api.common.v1.BaseResponseR\x04base\"Z\n" +
	"\x0fLikeListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12.\n" +
	"\x04page\x18\x02 \x01(\v2\x1a.api.common.v1.PageRequestR\x04page\"\x9e\x01\n" +
	"\rLikeListReply\x12/\n" +
	"\x04base\x18\x01 \x01(\v2\x1b.api.common.v1.BaseResponseR\x04base\x12+\n" +
	"\x06videos\x18\x02 \x03(\v2\x13.api.video.v1.VideoR\x06videos\x12/\n" +
	"\x04page\x18\x03 \x01(\v2\x1b.api.common.v1.PageResponseR\x04page\"j\n" +
	"\x14CommentActionRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x03 \x01(\x03R\tcommentId\"|\n" +
	"\x12CommentActionReply\x12/\n" +
	"\x04base\x18\x01 \x01(\v2\x1b.api.common.v1.BaseResponseR\x04base\x125\n" +
	"\acomment\x18\x02 \x01(\v2\x1b.api.interaction.v1.CommentR\acomment\"_\n" +
	"\x12CommentListRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\x03R\avideoId\x12.\n" +
	"\x04page\x18\x02 \x01(\v2\x1a.api.common.v1.PageRequestR\x04page\"\xad\x01\n" +
	"\x10CommentListReply\x12/\n" +
	"\x04base\x18\x01 \x01(\v2\x1b.api.common.v1.BaseResponseR\x04base\x127\n" +
	"\bcomments\x18\x02 \x03(\v2\x1b.api.interaction.v1.CommentR\bcomments\x12/\n" +
	"\x04page\x18\x03 \x01(\v2\x1b.api.common.v1.PageResponseR\x04page\"5\n" +
	"\x14DeleteCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03R\tcommentId\"E\n" +
	"\x12DeleteCommentReply\x12/\n" +
	"\x04base\x18\x01 \x01(\v2\x1b.api.common.v1.BaseResponseR\x04base2\xe5\x03\n" +
	"\x12InteractionService\x12X\n" +
	"\n" +
	"LikeAction\x12%.api.interaction.v1.LikeActionRequest\x1a#.api.interaction.v1.LikeActionReply\x12R\n" +
	"\bLikeList\x12#.api.interaction.v1.LikeListRequest\x1a!.api.interaction.v1.LikeListReply\x12a\n" +
	"\rCommentAction\x12(.api.interaction.v1.CommentActionRequest\x1a&.api.interaction.v1.CommentActionReply\x12[\n" +
	"\vCommentList\x12&.api.interaction.v1.CommentListRequest\x1a$.api.interaction.v1.CommentListReply\x12a\n" +
	"\rDeleteComment\x12(.api.interaction.v1.DeleteCommentRequest\x1a&.api.interaction.v1.DeleteCommentReplyB#Z!west2-video/api/interaction/v1;v1b\x06proto3"

var (
	file_api_interaction_interaction_proto_rawDescOnce sync.Once
	file_api_interaction_interaction_proto_rawDescData []byte
)

func file_api_interaction_interaction_proto_rawDescGZIP() []byte {
	file_api_interaction_interaction_proto_rawDescOnce.Do(func() {
		file_api_interaction_interaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_interaction_interaction_proto_rawDesc), len(file_api_interaction_interaction_proto_rawDesc)))
	})
	return file_api_interaction_interaction_proto_rawDescData
}

var file_api_interaction_interaction_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_interaction_interaction_proto_goTypes = []any{
	(*Comment)(nil),              // 0: api.interaction.v1.Comment
	(*LikeActionRequest)(nil),    // 1: api.interaction.v1.LikeActionRequest
	(*LikeActionReply)(nil),      // 2: api.interaction.v1.LikeActionReply
	(*LikeListRequest)(nil),      // 3: api.interaction.v1.LikeListRequest
	(*LikeListReply)(nil),        // 4: api.interaction.v1.LikeListReply
	(*CommentActionRequest)(nil), // 5: api.interaction.v1.CommentActionRequest
	(*CommentActionReply)(nil),   // 6: api.interaction.v1.CommentActionReply
	(*CommentListRequest)(nil),   // 7: api.interaction.v1.CommentListRequest
	(*CommentListReply)(nil),     // 8: api.interaction.v1.CommentListReply
	(*DeleteCommentRequest)(nil), // 9: api.interaction.v1.DeleteCommentRequest
	(*DeleteCommentReply)(nil),   // 10: api.interaction.v1.DeleteCommentReply
	(*v1.User)(nil),              // 11: api.user.v1.User
	(*v11.Timestamp)(nil),        // 12: api.common.v1.Timestamp
	(*v11.BaseResponse)(nil),     // 13: api.common.v1.BaseResponse
	(*v11.PageRequest)(nil),      // 14: api.common.v1.PageRequest
	(*v12.Video)(nil),            // 15: api.video.v1.Video
	(*v11.PageResponse)(nil),     // 16: api.common.v1.PageResponse
}
var file_api_interaction_interaction_proto_depIdxs = []int32{
	11, // 0: api.interaction.v1.Comment.user:type_name -> api.user.v1.User
	12, // 1: api.interaction.v1.Comment.created_at:type_name -> api.common.v1.Timestamp
	12, // 2: api.interaction.v1.Comment.updated_at:type_name -> api.common.v1.Timestamp
	12, // 3: api.interaction.v1.Comment.deleted_at:type_name -> api.common.v1.Timestamp
	13, // 4: api.interaction.v1.LikeActionReply.base:type_name -> api.common.v1.BaseResponse
	14, // 5: api.interaction.v1.LikeListRequest.page:type_name -> api.common.v1.PageRequest
	13, // 6: api.interaction.v1.LikeListReply.base:type_name -> api.common.v1.BaseResponse
	15, // 7: api.interaction.v1.LikeListReply.videos:type_name -> api.video.v1.Video
	16, // 8: api.interaction.v1.LikeListReply.page:type_name -> api.common.v1.PageResponse
	13, // 9: api.interaction.v1.CommentActionReply.base:type_name -> api.common.v1.BaseResponse
	0,  // 10: api.interaction.v1.CommentActionReply.comment:type_name -> api.interaction.v1.Comment
	14, // 11: api.interaction.v1.CommentListRequest.page:type_name -> api.common.v1.PageRequest
	13, // 12: api.interaction.v1.CommentListReply.base:type_name -> api.common.v1.BaseResponse
	0,  // 13: api.interaction.v1.CommentListReply.comments:type_name -> api.interaction.v1.Comment
	16, // 14: api.interaction.v1.CommentListReply.page:type_name -> api.common.v1.PageResponse
	13, // 15: api.interaction.v1.DeleteCommentReply.base:type_name -> api.common.v1.BaseResponse
	1,  // 16: api.interaction.v1.InteractionService.LikeAction:input_type -> api.interaction.v1.LikeActionRequest
	3,  // 17: api.interaction.v1.InteractionService.LikeList:input_type -> api.interaction.v1.LikeListRequest
	5,  // 18: api.interaction.v1.InteractionService.CommentAction:input_type -> api.interaction.v1.CommentActionRequest
	7,  // 19: api.interaction.v1.InteractionService.CommentList:input_type -> api.interaction.v1.CommentListRequest
	9,  // 20: api.interaction.v1.InteractionService.DeleteComment:input_type -> api.interaction.v1.DeleteCommentRequest
	2,  // 21: api.interaction.v1.InteractionService.LikeAction:output_type -> api.interaction.v1.LikeActionReply
	4,  // 22: api.interaction.v1.InteractionService.LikeList:output_type -> api.interaction.v1.LikeListReply
	6,  // 23: api.interaction.v1.InteractionService.CommentAction:output_type -> api.interaction.v1.CommentActionReply
	8,  // 24: api.interaction.v1.InteractionService.CommentList:output_type -> api.interaction.v1.CommentListReply
	10, // 25: api.interaction.v1.InteractionService.DeleteComment:output_type -> api.interaction.v1.DeleteCommentReply
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_interaction_interaction_proto_init() }
func file_api_interaction_interaction_proto_init() {
	if File_api_interaction_interaction_proto != nil {
		return
	}
	file_api_interaction_interaction_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_interaction_interaction_proto_rawDesc), len(file_api_interaction_interaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_interaction_interaction_proto_goTypes,
		DependencyIndexes: file_api_interaction_interaction_proto_depIdxs,
		MessageInfos:      file_api_interaction_interaction_proto_msgTypes,
	}.Build()
	File_api_interaction_interaction_proto = out.File
	file_api_interaction_interaction_proto_goTypes = nil
	file_api_interaction_interaction_proto_depIdxs = nil
}
