// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: api/social/social.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	v1 "west2-video/api/common/v1"
	_ "west2-video/api/user/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========= 社交对象（文档“社交对象” Schema） =========
type SocialUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	AvatarUrl     string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Signature     string                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	IsFollow      bool                   `protobuf:"varint,6,opt,name=is_follow,json=isFollow,proto3" json:"is_follow,omitempty"`
	CreatedAt     *v1.Timestamp          `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SocialUser) Reset() {
	*x = SocialUser{}
	mi := &file_api_social_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SocialUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SocialUser) ProtoMessage() {}

func (x *SocialUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SocialUser.ProtoReflect.Descriptor instead.
func (*SocialUser) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{0}
}

func (x *SocialUser) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SocialUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SocialUser) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *SocialUser) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *SocialUser) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SocialUser) GetIsFollow() bool {
	if x != nil {
		return x.IsFollow
	}
	return false
}

func (x *SocialUser) GetCreatedAt() *v1.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ========= 聊天消息体（WebSocket 聊天使用） =========
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUserId    int64                  `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId,proto3" json:"from_user_id,omitempty"`
	ToUserId      int64                  `protobuf:"varint,2,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *v1.Timestamp          `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_api_social_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{1}
}

func (x *ChatMessage) GetFromUserId() int64 {
	if x != nil {
		return x.FromUserId
	}
	return 0
}

func (x *ChatMessage) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatMessage) GetCreatedAt() *v1.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ========= 关注操作 =========
type FollowActionRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ToUserId int64                  `protobuf:"varint,1,opt,name=to_user_id,json=toUserId,proto3" json:"to_user_id,omitempty"`
	// action_type: 1 关注, 2 取关
	ActionType    int32 `protobuf:"varint,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowActionRequest) Reset() {
	*x = FollowActionRequest{}
	mi := &file_api_social_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowActionRequest) ProtoMessage() {}

func (x *FollowActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowActionRequest.ProtoReflect.Descriptor instead.
func (*FollowActionRequest) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{2}
}

func (x *FollowActionRequest) GetToUserId() int64 {
	if x != nil {
		return x.ToUserId
	}
	return 0
}

func (x *FollowActionRequest) GetActionType() int32 {
	if x != nil {
		return x.ActionType
	}
	return 0
}

type FollowActionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v1.BaseResponse       `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowActionReply) Reset() {
	*x = FollowActionReply{}
	mi := &file_api_social_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowActionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowActionReply) ProtoMessage() {}

func (x *FollowActionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowActionReply.ProtoReflect.Descriptor instead.
func (*FollowActionReply) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{3}
}

func (x *FollowActionReply) GetBase() *v1.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

// ========= 关注列表 =========
type FollowListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 指定用户
	Page          *v1.PageRequest        `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowListRequest) Reset() {
	*x = FollowListRequest{}
	mi := &file_api_social_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowListRequest) ProtoMessage() {}

func (x *FollowListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowListRequest.ProtoReflect.Descriptor instead.
func (*FollowListRequest) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{4}
}

func (x *FollowListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FollowListRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type FollowListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v1.BaseResponse       `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Users         []*SocialUser          `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowListReply) Reset() {
	*x = FollowListReply{}
	mi := &file_api_social_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowListReply) ProtoMessage() {}

func (x *FollowListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowListReply.ProtoReflect.Descriptor instead.
func (*FollowListReply) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{5}
}

func (x *FollowListReply) GetBase() *v1.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *FollowListReply) GetUsers() []*SocialUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *FollowListReply) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// ========= 粉丝列表 =========
type FollowerListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 指定用户
	Page          *v1.PageRequest        `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowerListRequest) Reset() {
	*x = FollowerListRequest{}
	mi := &file_api_social_social_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowerListRequest) ProtoMessage() {}

func (x *FollowerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowerListRequest.ProtoReflect.Descriptor instead.
func (*FollowerListRequest) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{6}
}

func (x *FollowerListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FollowerListRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type FollowerListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v1.BaseResponse       `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Users         []*SocialUser          `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowerListReply) Reset() {
	*x = FollowerListReply{}
	mi := &file_api_social_social_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowerListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowerListReply) ProtoMessage() {}

func (x *FollowerListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowerListReply.ProtoReflect.Descriptor instead.
func (*FollowerListReply) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{7}
}

func (x *FollowerListReply) GetBase() *v1.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *FollowerListReply) GetUsers() []*SocialUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *FollowerListReply) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// ========= 好友列表 =========
type FriendListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *v1.PageRequest        `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendListRequest) Reset() {
	*x = FriendListRequest{}
	mi := &file_api_social_social_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListRequest) ProtoMessage() {}

func (x *FriendListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListRequest.ProtoReflect.Descriptor instead.
func (*FriendListRequest) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{8}
}

func (x *FriendListRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type FriendListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v1.BaseResponse       `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Users         []*SocialUser          `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendListReply) Reset() {
	*x = FriendListReply{}
	mi := &file_api_social_social_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListReply) ProtoMessage() {}

func (x *FriendListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_social_social_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListReply.ProtoReflect.Descriptor instead.
func (*FriendListReply) Descriptor() ([]byte, []int) {
	return file_api_social_social_proto_rawDescGZIP(), []int{9}
}

func (x *FriendListReply) GetBase() *v1.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *FriendListReply) GetUsers() []*SocialUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *FriendListReply) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_api_social_social_proto protoreflect.FileDescriptor

const file_api_social_social_proto_rawDesc = "" +
	"\n" +
	"\x17api/social/social.proto\x12\rapi.social.v1\x1a\x15api/common/base.proto\x1a\x13api/user/user.proto\"\xe7\x01\n" +
	"\n" +
	"SocialUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\tR\tsignature\x12\x1b\n" +
	"\tis_follow\x18\x06 \x01(\bR\bisFollow\x127\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x18.api.common.v1.TimestampR\tcreatedAt\"\xa0\x01\n" +
	"\vChatMessage\x12 \n" +
	"\ffrom_user_id\x18\x01 \x01(\x03R\n" +
	"fromUserId\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x02 \x01(\x03R\btoUserId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x127\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x18.api.common.v1.TimestampR\tcreatedAt\"T\n" +
	"\x13FollowActionRequest\x12\x1c\n" +
	"\n" +
	"to_user_id\x18\x01 \x01(\x03R\btoUserId\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\x05R\n" +
	"actionType\"D\n" +
	"\x11FollowActionReply\x12/\n" +
	"\x04base\x18\x01 \x01(\v2\x1b.api.common.v1.BaseResponseR\x04base\"\\\n" +
	"\x11FollowListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12.\n" +
	"\x04page\x18\x02 \x01(\v2\x1a.api.common.v1.PageRequestR\x04page\"\xa4\x01\n" +
	"\x0fFollowListReply\x12/\n" +
	"\x04base\x18\x01 \x01(\v2\x1b.api.common.v1.BaseResponseR\x04base\x12/\n" +
	"\x05users\x18\x02 \x03(\v2\x19.api.social.v1.SocialUserR\x05users\x12/\n" +
	"\x04page\x18\x03 \x01(\v2\x1b.api.common.v1.PageResponseR\x04page\"^\n" +
	"\x13FollowerListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12.\n" +
	"\x04page\x18\x02 \x01(\v2\x1a.api.common.v1.PageRequestR\x04page\"\xa6\x01\n" +
	"\x11FollowerListReply\x12/\n" +
	"\x04base\x18\x01 \x01(\v2\x1b.api.common.v1.BaseResponseR\x04base\x12/\n" +
	"\x05users\x18\x02 \x03(\v2\x19.api.social.v1.SocialUserR\x05users\x12/\n" +
	"\x04page\x18\x03 \x01(\v2\x1b.api.common.v1.PageResponseR\x04page\"C\n" +
	"\x11FriendListRequest\x12.\n" +
	"\x04page\x18\x01 \x01(\v2\x1a.api.common.v1.PageRequestR\x04page\"\xa4\x01\n" +
	"\x0fFriendListReply\x12/\n" +
	"\x04base\x18\x01 \x01(\v2\x1b.api.common.v1.BaseResponseR\x04base\x12/\n" +
	"\x05users\x18\x02 \x03(\v2\x19.api.social.v1.SocialUserR\x05users\x12/\n" +
	"\x04page\x18\x03 \x01(\v2\x1b.api.common.v1.PageResponseR\x04page2\xdb\x02\n" +
	"\rSocialService\x12T\n" +
	"\fFollowAction\x12\".api.social.v1.FollowActionRequest\x1a .api.social.v1.FollowActionReply\x12N\n" +
	"\n" +
	"FollowList\x12 .api.social.v1.FollowListRequest\x1a\x1e.api.social.v1.FollowListReply\x12T\n" +
	"\fFollowerList\x12\".api.social.v1.FollowerListRequest\x1a .api.social.v1.FollowerListReply\x12N\n" +
	"\n" +
	"FriendList\x12 .api.social.v1.FriendListRequest\x1a\x1e.api.social.v1.FriendListReplyB\x1eZ\x1cwest2-video/api/social/v1;v1b\x06proto3"

var (
	file_api_social_social_proto_rawDescOnce sync.Once
	file_api_social_social_proto_rawDescData []byte
)

func file_api_social_social_proto_rawDescGZIP() []byte {
	file_api_social_social_proto_rawDescOnce.Do(func() {
		file_api_social_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_social_social_proto_rawDesc), len(file_api_social_social_proto_rawDesc)))
	})
	return file_api_social_social_proto_rawDescData
}

var file_api_social_social_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_social_social_proto_goTypes = []any{
	(*SocialUser)(nil),          // 0: api.social.v1.SocialUser
	(*ChatMessage)(nil),         // 1: api.social.v1.ChatMessage
	(*FollowActionRequest)(nil), // 2: api.social.v1.FollowActionRequest
	(*FollowActionReply)(nil),   // 3: api.social.v1.FollowActionReply
	(*FollowListRequest)(nil),   // 4: api.social.v1.FollowListRequest
	(*FollowListReply)(nil),     // 5: api.social.v1.FollowListReply
	(*FollowerListRequest)(nil), // 6: api.social.v1.FollowerListRequest
	(*FollowerListReply)(nil),   // 7: api.social.v1.FollowerListReply
	(*FriendListRequest)(nil),   // 8: api.social.v1.FriendListRequest
	(*FriendListReply)(nil),     // 9: api.social.v1.FriendListReply
	(*v1.Timestamp)(nil),        // 10: api.common.v1.Timestamp
	(*v1.BaseResponse)(nil),     // 11: api.common.v1.BaseResponse
	(*v1.PageRequest)(nil),      // 12: api.common.v1.PageRequest
	(*v1.PageResponse)(nil),     // 13: api.common.v1.PageResponse
}
var file_api_social_social_proto_depIdxs = []int32{
	10, // 0: api.social.v1.SocialUser.created_at:type_name -> api.common.v1.Timestamp
	10, // 1: api.social.v1.ChatMessage.created_at:type_name -> api.common.v1.Timestamp
	11, // 2: api.social.v1.FollowActionReply.base:type_name -> api.common.v1.BaseResponse
	12, // 3: api.social.v1.FollowListRequest.page:type_name -> api.common.v1.PageRequest
	11, // 4: api.social.v1.FollowListReply.base:type_name -> api.common.v1.BaseResponse
	0,  // 5: api.social.v1.FollowListReply.users:type_name -> api.social.v1.SocialUser
	13, // 6: api.social.v1.FollowListReply.page:type_name -> api.common.v1.PageResponse
	12, // 7: api.social.v1.FollowerListRequest.page:type_name -> api.common.v1.PageRequest
	11, // 8: api.social.v1.FollowerListReply.base:type_name -> api.common.v1.BaseResponse
	0,  // 9: api.social.v1.FollowerListReply.users:type_name -> api.social.v1.SocialUser
	13, // 10: api.social.v1.FollowerListReply.page:type_name -> api.common.v1.PageResponse
	12, // 11: api.social.v1.FriendListRequest.page:type_name -> api.common.v1.PageRequest
	11, // 12: api.social.v1.FriendListReply.base:type_name -> api.common.v1.BaseResponse
	0,  // 13: api.social.v1.FriendListReply.users:type_name -> api.social.v1.SocialUser
	13, // 14: api.social.v1.FriendListReply.page:type_name -> api.common.v1.PageResponse
	2,  // 15: api.social.v1.SocialService.FollowAction:input_type -> api.social.v1.FollowActionRequest
	4,  // 16: api.social.v1.SocialService.FollowList:input_type -> api.social.v1.FollowListRequest
	6,  // 17: api.social.v1.SocialService.FollowerList:input_type -> api.social.v1.FollowerListRequest
	8,  // 18: api.social.v1.SocialService.FriendList:input_type -> api.social.v1.FriendListRequest
	3,  // 19: api.social.v1.SocialService.FollowAction:output_type -> api.social.v1.FollowActionReply
	5,  // 20: api.social.v1.SocialService.FollowList:output_type -> api.social.v1.FollowListReply
	7,  // 21: api.social.v1.SocialService.FollowerList:output_type -> api.social.v1.FollowerListReply
	9,  // 22: api.social.v1.SocialService.FriendList:output_type -> api.social.v1.FriendListReply
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_social_social_proto_init() }
func file_api_social_social_proto_init() {
	if File_api_social_social_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_social_social_proto_rawDesc), len(file_api_social_social_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_social_social_proto_goTypes,
		DependencyIndexes: file_api_social_social_proto_depIdxs,
		MessageInfos:      file_api_social_social_proto_msgTypes,
	}.Build()
	File_api_social_social_proto = out.File
	file_api_social_social_proto_goTypes = nil
	file_api_social_social_proto_depIdxs = nil
}
