// Code generated by hertz generator. DO NOT EDIT.

package user

import (

	"github.com/cloudwego/hertz/pkg/app/server"
	"west2-video/gateway/biz/handler"
	"west2-video/gateway/biz/midd"
	"west2-video/gateway/biz/router/routerRepo"
)
func NewVideoRouter()*VideoRouter {
	return &VideoRouter{}
}
type VideoRouter struct{

}
// GeneratedRegister registers routers generated by IDL.
func (rr *VideoRouter)Router(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	// 视频相关路由
	video := r.Group("/video")
	{
		video.GET("/feed", handler.Feed)                               // 视频流
		video.POST("/publish",midd.AuthMiddleware(), handler.Publish) // 投稿
		video.GET("/list",midd.AuthMiddleware(), handler.PublishList)                // 发布列表
		video.GET("/popular",midd.AuthMiddleware(), handler.HotRanking)                  // 热门排行榜
		video.GET("/watch",midd.AuthMiddleware(), handler.Watch)                  // 观看视频
		video.POST("/search",midd.AuthMiddleware(), handler.SearchVideo)                      // 搜索视频
	}

}
func init() {
	router := NewVideoRouter()
	routerRepo.Register(router)
}