server:
  host: "127.0.0.1"
  port: 8080
  mode: "dev"

etcd:
  addrs:
    - "127.0.0.1:2379"

services:
  user_service: "user"
  video_service: "video"
  interaction_service: "interaction"
  social_service: "social"

jwt:
  accessExp: 604800 #7天
  refreshExp: 1209600
  accessSecret: west2
  refreshSecret: cai

zap:
  debugFileName: "E:\\west2\\04\\west2_04\\logs\\debug\\user-debug.log"
  infoFileName: "E:\\west2\\04\\west2_04\\logs\\debug\\user-info.log"
  warnFileName: "E:\\west2\\04\\west2_04\\logs\\debug\\user-error.log"
  maxSize: 500,
  maxAge: 28,
  MaxBackups: 3