// Code generated by hertz generator. DO NOT EDIT.

package user

import (

	"github.com/cloudwego/hertz/pkg/app/server"
	"west2-video/gateway/biz/handler"
	"west2-video/gateway/biz/midd"
	"west2-video/gateway/biz/router/routerRepo"
)
func NewSocialRouter()*SocialRouter {
	return &SocialRouter{}
}
type SocialRouter struct{

}
// GeneratedRegister registers routers generated by IDL.
func (rr *SocialRouter)Router(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	// 视频相关路由
	// 社交相关路由
	social := r.Group("").Use(midd.AuthMiddleware())
	{
		social.POST("/relation/action",  handler.FollowAction)   // 关注操作
		social.GET("/following/list", handler.FollowList)     // 关注列表
		social.GET("/follower/list", handler.FollowerList)  // 粉丝列表
		social.GET("/friends/list",  handler.FriendList) // 好友列表
	}

}
func init() {
	router := NewSocialRouter()
	routerRepo.Register(router)
}