// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: api/video/video.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	v11 "west2-video/api/common/v1"
	v1 "west2-video/api/user/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========= 视频通用结构（文档“视频” Schema） =========
type Video struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      int64                  `protobuf:"varint,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Author        *v1.User               `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	PlayUrl       string                 `protobuf:"bytes,4,opt,name=play_url,json=playUrl,proto3" json:"play_url,omitempty"` // 视频访问地址
	CoverUrl      string                 `protobuf:"bytes,5,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	FavoriteCount int64                  `protobuf:"varint,8,opt,name=favorite_count,json=favoriteCount,proto3" json:"favorite_count,omitempty"` // 点赞数
	CommentCount  int64                  `protobuf:"varint,9,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	VisitCount    int64                  `protobuf:"varint,10,opt,name=visit_count,json=visitCount,proto3" json:"visit_count,omitempty"` // 点击/播放次数（用于热门榜）
	CreatedAt     *v11.Timestamp         `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_api_video_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_api_video_video_proto_rawDescGZIP(), []int{0}
}

func (x *Video) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Video) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Video) GetAuthor() *v1.User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Video) GetPlayUrl() string {
	if x != nil {
		return x.PlayUrl
	}
	return ""
}

func (x *Video) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

func (x *Video) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Video) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Video) GetFavoriteCount() int64 {
	if x != nil {
		return x.FavoriteCount
	}
	return 0
}

func (x *Video) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *Video) GetVisitCount() int64 {
	if x != nil {
		return x.VisitCount
	}
	return 0
}

func (x *Video) GetCreatedAt() *v11.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ========= 视频流 / Feed =========
type FeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LatestTime    int64                  `protobuf:"varint,1,opt,name=latest_time,json=latestTime,proto3" json:"latest_time,omitempty"` // Unix 秒；0 表示当前时间
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`       // 可选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedRequest) Reset() {
	*x = FeedRequest{}
	mi := &file_api_video_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedRequest) ProtoMessage() {}

func (x *FeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedRequest.ProtoReflect.Descriptor instead.
func (*FeedRequest) Descriptor() ([]byte, []int) {
	return file_api_video_video_proto_rawDescGZIP(), []int{1}
}

func (x *FeedRequest) GetLatestTime() int64 {
	if x != nil {
		return x.LatestTime
	}
	return 0
}

func (x *FeedRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type FeedReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v11.BaseResponse      `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	VideoList     []*Video               `protobuf:"bytes,2,rep,name=video_list,json=videoList,proto3" json:"video_list,omitempty"`
	NextTime      int64                  `protobuf:"varint,3,opt,name=next_time,json=nextTime,proto3" json:"next_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedReply) Reset() {
	*x = FeedReply{}
	mi := &file_api_video_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedReply) ProtoMessage() {}

func (x *FeedReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedReply.ProtoReflect.Descriptor instead.
func (*FeedReply) Descriptor() ([]byte, []int) {
	return file_api_video_video_proto_rawDescGZIP(), []int{2}
}

func (x *FeedReply) GetBase() *v11.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *FeedReply) GetVideoList() []*Video {
	if x != nil {
		return x.VideoList
	}
	return nil
}

func (x *FeedReply) GetNextTime() int64 {
	if x != nil {
		return x.NextTime
	}
	return 0
}

// ========= 投稿 =========
type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // 视频原始数据（multipart/form-data 对应）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_api_video_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_api_video_video_proto_rawDescGZIP(), []int{3}
}

func (x *PublishRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PublishRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PublishRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PublishReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v11.BaseResponse      `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishReply) Reset() {
	*x = PublishReply{}
	mi := &file_api_video_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishReply) ProtoMessage() {}

func (x *PublishReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishReply.ProtoReflect.Descriptor instead.
func (*PublishReply) Descriptor() ([]byte, []int) {
	return file_api_video_video_proto_rawDescGZIP(), []int{4}
}

func (x *PublishReply) GetBase() *v11.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

// ========= 发布列表 =========
type PublishListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          *v11.PageRequest       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishListRequest) Reset() {
	*x = PublishListRequest{}
	mi := &file_api_video_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishListRequest) ProtoMessage() {}

func (x *PublishListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishListRequest.ProtoReflect.Descriptor instead.
func (*PublishListRequest) Descriptor() ([]byte, []int) {
	return file_api_video_video_proto_rawDescGZIP(), []int{5}
}

func (x *PublishListRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PublishListRequest) GetPage() *v11.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type PublishListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v11.BaseResponse      `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	VideoList     []*Video               `protobuf:"bytes,2,rep,name=video_list,json=videoList,proto3" json:"video_list,omitempty"`
	Page          *v11.PageResponse      `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishListReply) Reset() {
	*x = PublishListReply{}
	mi := &file_api_video_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishListReply) ProtoMessage() {}

func (x *PublishListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishListReply.ProtoReflect.Descriptor instead.
func (*PublishListReply) Descriptor() ([]byte, []int) {
	return file_api_video_video_proto_rawDescGZIP(), []int{6}
}

func (x *PublishListReply) GetBase() *v11.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *PublishListReply) GetVideoList() []*Video {
	if x != nil {
		return x.VideoList
	}
	return nil
}

func (x *PublishListReply) GetPage() *v11.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// ========= 热门排行榜 =========
type HotRankingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *v11.PageRequest       `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotRankingRequest) Reset() {
	*x = HotRankingRequest{}
	mi := &file_api_video_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotRankingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotRankingRequest) ProtoMessage() {}

func (x *HotRankingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotRankingRequest.ProtoReflect.Descriptor instead.
func (*HotRankingRequest) Descriptor() ([]byte, []int) {
	return file_api_video_video_proto_rawDescGZIP(), []int{7}
}

func (x *HotRankingRequest) GetPage() *v11.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type HotRankingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v11.BaseResponse      `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	VideoList     []*Video               `protobuf:"bytes,2,rep,name=video_list,json=videoList,proto3" json:"video_list,omitempty"`
	Page          *v11.PageResponse      `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotRankingReply) Reset() {
	*x = HotRankingReply{}
	mi := &file_api_video_video_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotRankingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotRankingReply) ProtoMessage() {}

func (x *HotRankingReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_video_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotRankingReply.ProtoReflect.Descriptor instead.
func (*HotRankingReply) Descriptor() ([]byte, []int) {
	return file_api_video_video_proto_rawDescGZIP(), []int{8}
}

func (x *HotRankingReply) GetBase() *v11.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *HotRankingReply) GetVideoList() []*Video {
	if x != nil {
		return x.VideoList
	}
	return nil
}

func (x *HotRankingReply) GetPage() *v11.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

// ========= 搜索视频 =========
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keywords      string                 `protobuf:"bytes,1,opt,name=keywords,proto3" json:"keywords,omitempty"` // 搜索关键字
	Page          *v11.PageRequest       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_video_video_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_video_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_video_video_proto_rawDescGZIP(), []int{9}
}

func (x *SearchRequest) GetKeywords() string {
	if x != nil {
		return x.Keywords
	}
	return ""
}

func (x *SearchRequest) GetPage() *v11.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type SearchReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *v11.BaseResponse      `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	VideoList     []*Video               `protobuf:"bytes,2,rep,name=video_list,json=videoList,proto3" json:"video_list,omitempty"`
	Page          *v11.PageResponse      `protobuf:"bytes,3,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchReply) Reset() {
	*x = SearchReply{}
	mi := &file_api_video_video_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchReply) ProtoMessage() {}

func (x *SearchReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_video_video_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchReply.ProtoReflect.Descriptor instead.
func (*SearchReply) Descriptor() ([]byte, []int) {
	return file_api_video_video_proto_rawDescGZIP(), []int{10}
}

func (x *SearchReply) GetBase() *v11.BaseResponse {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *SearchReply) GetVideoList() []*Video {
	if x != nil {
		return x.VideoList
	}
	return nil
}

func (x *SearchReply) GetPage() *v11.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

var File_api_video_video_proto protoreflect.FileDescriptor

const file_api_video_video_proto_rawDesc = "" +
	"\n" +
	"\x15api/video/video.proto\x12\fapi.video.v1\x1a\x15api/common/base.proto\x1a\x13api/user/user.proto\"\xf5\x02\n" +
	"\x05Video\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\x03R\bauthorId\x12)\n" +
	"\x06author\x18\x03 \x01(\v2\x11.api.user.v1.UserR\x06author\x12\x19\n" +
	"\bplay_url\x18\x04 \x01(\tR\aplayUrl\x12\x1b\n" +
	"\tcover_url\x18\x05 \x01(\tR\bcoverUrl\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12%\n" +
	"\x0efavorite_count\x18\b \x01(\x03R\rfavoriteCount\x12#\n" +
	"\rcomment_count\x18\t \x01(\x03R\fcommentCount\x12\x1f\n" +
	"\vvisit_count\x18\n" +
	" \x01(\x03R\n" +
	"visitCount\x127\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x18.api.common.v1.TimestampR\tcreatedAt\"K\n" +
	"\vFeedRequest\x12\x1f\n" +
	"\vlatest_time\x18\x01 \x01(\x03R\n" +
	"latestTime\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x8d\x01\n" +
	"\tFeedReply\x12/\n" +
	"\x04base\x18\x01 \x01(\v2\x1b.api.common.v1.BaseResponseR\x04base\x122\n" +
	"\n" +
	"video_list\x18\x02 \x03(\v2\x13.api.video.v1.VideoR\tvideoList\x12\x1b\n" +
	"\tnext_time\x18\x03 \x01(\x03R\bnextTime\"\\\n" +
	"\x0ePublishRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"?\n" +
	"\fPublishReply\x12/\n" +
	"\x04base\x18\x01 \x01(\v2\x1b.api.common.v1.BaseResponseR\x04base\"]\n" +
	"\x12PublishListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12.\n" +
	"\x04page\x18\x02 \x01(\v2\x1a.api.common.v1.PageRequestR\x04page\"\xa8\x01\n" +
	"\x10PublishListReply\x12/\n" +
	"\x04base\x18\x01 \x01(\v2\x1b.api.common.v1.BaseResponseR\x04base\x122\n" +
	"\n" +
	"video_list\x18\x02 \x03(\v2\x13.api.video.v1.VideoR\tvideoList\x12/\n" +
	"\x04page\x18\x03 \x01(\v2\x1b.api.common.v1.PageResponseR\x04page\"C\n" +
	"\x11HotRankingRequest\x12.\n" +
	"\x04page\x18\x01 \x01(\v2\x1a.api.common.v1.PageRequestR\x04page\"\xa7\x01\n" +
	"\x0fHotRankingReply\x12/\n" +
	"\x04base\x18\x01 \x01(\v2\x1b.api.common.v1.BaseResponseR\x04base\x122\n" +
	"\n" +
	"video_list\x18\x02 \x03(\v2\x13.api.video.v1.VideoR\tvideoList\x12/\n" +
	"\x04page\x18\x03 \x01(\v2\x1b.api.common.v1.PageResponseR\x04page\"[\n" +
	"\rSearchRequest\x12\x1a\n" +
	"\bkeywords\x18\x01 \x01(\tR\bkeywords\x12.\n" +
	"\x04page\x18\x02 \x01(\v2\x1a.api.common.v1.PageRequestR\x04page\"\xa3\x01\n" +
	"\vSearchReply\x12/\n" +
	"\x04base\x18\x01 \x01(\v2\x1b.api.common.v1.BaseResponseR\x04base\x122\n" +
	"\n" +
	"video_list\x18\x02 \x03(\v2\x13.api.video.v1.VideoR\tvideoList\x12/\n" +
	"\x04page\x18\x03 \x01(\v2\x1b.api.common.v1.PageResponseR\x04page2\xf0\x02\n" +
	"\fVideoService\x12:\n" +
	"\x04Feed\x12\x19.api.video.v1.FeedRequest\x1a\x17.api.video.v1.FeedReply\x12C\n" +
	"\aPublish\x12\x1c.api.video.v1.PublishRequest\x1a\x1a.api.video.v1.PublishReply\x12O\n" +
	"\vPublishList\x12 .api.video.v1.PublishListRequest\x1a\x1e.api.video.v1.PublishListReply\x12L\n" +
	"\n" +
	"HotRanking\x12\x1f.api.video.v1.HotRankingRequest\x1a\x1d.api.video.v1.HotRankingReply\x12@\n" +
	"\x06Search\x12\x1b.api.video.v1.SearchRequest\x1a\x19.api.video.v1.SearchReplyB\x1dZ\x1bwest2-video/api/video/v1;v1b\x06proto3"

var (
	file_api_video_video_proto_rawDescOnce sync.Once
	file_api_video_video_proto_rawDescData []byte
)

func file_api_video_video_proto_rawDescGZIP() []byte {
	file_api_video_video_proto_rawDescOnce.Do(func() {
		file_api_video_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_video_video_proto_rawDesc), len(file_api_video_video_proto_rawDesc)))
	})
	return file_api_video_video_proto_rawDescData
}

var file_api_video_video_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_video_video_proto_goTypes = []any{
	(*Video)(nil),              // 0: api.video.v1.Video
	(*FeedRequest)(nil),        // 1: api.video.v1.FeedRequest
	(*FeedReply)(nil),          // 2: api.video.v1.FeedReply
	(*PublishRequest)(nil),     // 3: api.video.v1.PublishRequest
	(*PublishReply)(nil),       // 4: api.video.v1.PublishReply
	(*PublishListRequest)(nil), // 5: api.video.v1.PublishListRequest
	(*PublishListReply)(nil),   // 6: api.video.v1.PublishListReply
	(*HotRankingRequest)(nil),  // 7: api.video.v1.HotRankingRequest
	(*HotRankingReply)(nil),    // 8: api.video.v1.HotRankingReply
	(*SearchRequest)(nil),      // 9: api.video.v1.SearchRequest
	(*SearchReply)(nil),        // 10: api.video.v1.SearchReply
	(*v1.User)(nil),            // 11: api.user.v1.User
	(*v11.Timestamp)(nil),      // 12: api.common.v1.Timestamp
	(*v11.BaseResponse)(nil),   // 13: api.common.v1.BaseResponse
	(*v11.PageRequest)(nil),    // 14: api.common.v1.PageRequest
	(*v11.PageResponse)(nil),   // 15: api.common.v1.PageResponse
}
var file_api_video_video_proto_depIdxs = []int32{
	11, // 0: api.video.v1.Video.author:type_name -> api.user.v1.User
	12, // 1: api.video.v1.Video.created_at:type_name -> api.common.v1.Timestamp
	13, // 2: api.video.v1.FeedReply.base:type_name -> api.common.v1.BaseResponse
	0,  // 3: api.video.v1.FeedReply.video_list:type_name -> api.video.v1.Video
	13, // 4: api.video.v1.PublishReply.base:type_name -> api.common.v1.BaseResponse
	14, // 5: api.video.v1.PublishListRequest.page:type_name -> api.common.v1.PageRequest
	13, // 6: api.video.v1.PublishListReply.base:type_name -> api.common.v1.BaseResponse
	0,  // 7: api.video.v1.PublishListReply.video_list:type_name -> api.video.v1.Video
	15, // 8: api.video.v1.PublishListReply.page:type_name -> api.common.v1.PageResponse
	14, // 9: api.video.v1.HotRankingRequest.page:type_name -> api.common.v1.PageRequest
	13, // 10: api.video.v1.HotRankingReply.base:type_name -> api.common.v1.BaseResponse
	0,  // 11: api.video.v1.HotRankingReply.video_list:type_name -> api.video.v1.Video
	15, // 12: api.video.v1.HotRankingReply.page:type_name -> api.common.v1.PageResponse
	14, // 13: api.video.v1.SearchRequest.page:type_name -> api.common.v1.PageRequest
	13, // 14: api.video.v1.SearchReply.base:type_name -> api.common.v1.BaseResponse
	0,  // 15: api.video.v1.SearchReply.video_list:type_name -> api.video.v1.Video
	15, // 16: api.video.v1.SearchReply.page:type_name -> api.common.v1.PageResponse
	1,  // 17: api.video.v1.VideoService.Feed:input_type -> api.video.v1.FeedRequest
	3,  // 18: api.video.v1.VideoService.Publish:input_type -> api.video.v1.PublishRequest
	5,  // 19: api.video.v1.VideoService.PublishList:input_type -> api.video.v1.PublishListRequest
	7,  // 20: api.video.v1.VideoService.HotRanking:input_type -> api.video.v1.HotRankingRequest
	9,  // 21: api.video.v1.VideoService.Search:input_type -> api.video.v1.SearchRequest
	2,  // 22: api.video.v1.VideoService.Feed:output_type -> api.video.v1.FeedReply
	4,  // 23: api.video.v1.VideoService.Publish:output_type -> api.video.v1.PublishReply
	6,  // 24: api.video.v1.VideoService.PublishList:output_type -> api.video.v1.PublishListReply
	8,  // 25: api.video.v1.VideoService.HotRanking:output_type -> api.video.v1.HotRankingReply
	10, // 26: api.video.v1.VideoService.Search:output_type -> api.video.v1.SearchReply
	22, // [22:27] is the sub-list for method output_type
	17, // [17:22] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_api_video_video_proto_init() }
func file_api_video_video_proto_init() {
	if File_api_video_video_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_video_video_proto_rawDesc), len(file_api_video_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_video_video_proto_goTypes,
		DependencyIndexes: file_api_video_video_proto_depIdxs,
		MessageInfos:      file_api_video_video_proto_msgTypes,
	}.Build()
	File_api_video_video_proto = out.File
	file_api_video_video_proto_goTypes = nil
	file_api_video_video_proto_depIdxs = nil
}
